channels:
- conda-forge
- defaults
dependencies:
- abtem=1.0.6
- atomap=0.4.2
- exspy=0.3.2
- ipykernel=7.0.0
- numpy=1.26.4
- scikit-image=0.25.2
- pip:
  - filelock==3.20.0
  - torch==2.8.0
  - torchvision==0.23.0
name: point_defects
